
name: Mirrors
on:
  push:
    branches: [ 'test/build-prod-repo-on-push' ]
jobs:
    mirror:
        name: Push to Mirror
        runs-on: ubuntu-latest
        steps:
            - name: Create build directory
              run: mkdir -p tmp/woocommerce-build

            - name: Extract and replace WooCommerce zip.
              working-directory: tmp/woocommerce-build
              run: |
                  mkdir woocommerce
                  touch woocommerce/README.md
                  echo "# WooCommerce Production (TEST)" >> woocommerce/README.md

            - name: Set up for mirror
              env:
                BUILD_BASE: tmp/woocommerce-build
              run: |
                  touch $BUILD_BASE/mirrors.txt
                  echo "woocommerce/woocommerce-production" >> $BUILD_BASE/mirrors.txt
                  mv $BUILD_BASE/woocommerce $BUILD_BASE/woocommerce-production
                  GIT_SLUG=woocommerce-production
                  
            - name: Push to mirror
              uses: Automattic/action-push-to-mirrors@v1
              with:
                  source-directory: ${{ github.workspace }}/monorepo
                  token: ${{ secrets.API_TOKEN_GITHUB }}
                  username: matticbot
                  working-directory: ${{ github.workspace }}/tmp/woocommerce-build
              timeout-minutes: 5  # 2021-01-18: Successful runs seem to take about half a minute.
