
name: Mirrors
on:
  push:
    branches: [ 'test/build-prod-repo-on-push' ]
jobs:
    build:
        name: Build WooCommerce zip
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Build
              id: build
              uses: woocommerce/action-build@trunk

            - name: Upload PR zip
              uses: actions/upload-artifact@v2
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  name: woocommerce
                  path: ${{ steps.build.outputs.zip_path }}
                  retention-days: 7
    mirror:
        name: Push to Mirror
        runs-on: ubuntu-latest
        needs: [build]
        steps:
            - name: Checkout monorepo
              uses: actions/checkout@v2
              with:
                  path: monorepo

            - name: Download WooCommerce ZIP
              uses: actions/download-artifact@v2
              with:
                  name: woocommerce
                  path: tmp/woocommerce-build

            - name: Extract and replace WooCommerce zip.
              working-directory: tmp/woocommerce-build
              run: |
                  unzip woocommerce.zip -d woocommerce

            - name: Set up for mirror
              env:
                BUILD_BASE: tmp/woocommerce-build
              run: |
                  touch $BUILD_BASE/mirrors.txt
                  echo "woocommerce/woocommerce-production" >> $BUILD_BASE/mirrors.txt
                  mv $BUILD_BASE/woocommerce $BUILD_BASE/woocommerce-production
                  
            - name: Push to mirror
              uses: Automattic/action-push-to-mirrors@v1
              with:
                  source-directory: ${{ github.workspace }}/monorepo
                  token: ${{ secrets.API_TOKEN_GITHUB }}
                  username: matticbot
                  working-directory: ${{ github.workspace }}/tmp/woocommerce-build
                  GIT_SLUG: woocommerce-production
              timeout-minutes: 5  # 2021-01-18: Successful runs seem to take about half a minute.
